export const SECTOR_OPTIONS = [
    { value: "ADM-Administracion", label: "🗃️ ADM – Administración" },
    { value: "AGC-Mantenimiento-Equipamiento-Medico", label: "🔧 AGC – Mantenimiento de Equipamiento Médico" },
    { value: "ANST-Anestesia", label: "💉 ANST – Anestesia" },
    { value: "APA-Anatomia-Patologica", label: "🔬 APA – Anatomía Patológica" },
    { value: "APS-Asistencia-Psicologica", label: "🧠 APS – Asistencia Psicológica" },
    { value: "ASMED-Asesor-Medico-Direccion", label: "👨‍⚕️ ASMED – Asesor Médico de la Dirección" },
    { value: "AUX-Auxiliares-Hoteleria", label: "🏨 AUX – Auxiliares de Hotelería" },
    { value: "CC-Contact-Center", label: "📞 CC – Contact Center" },
    { value: "CDI-Control-de-Infecciones", label: "🦠 CDI – Control de Infecciones" },
    { value: "CEXT-S1-Consultorios-Externos-Sede-1", label: "🏥 CEXT S1 – Consultorios Externos Sede 1" },
    { value: "CEXT-S2-Consultorios-Externos-Sede-2", label: "🏥 CEXT S2 – Consultorios Externos Sede 2" },
    { value: "CEXT-S3-Consultorios-Externos-Sede-3", label: "🏥 CEXT S3 – Consultorios Externos Sede 3" },
    { value: "CEXT-SFS-Consultorios-Externos-Sede-Santa-Fe", label: "🏥 CEXT SFS – Consultorios Externos Sede Santa Fé" },
    { value: "CHQ-Chequeo-Medico-Preventivo", label: "✅ CHQ – Chequeo Médico Preventivo" },
    { value: "CIT-Citologia", label: "🧫 CIT – Citología" },
    { value: "CYS-Compras-y-Suministro", label: "📦 CYS – Compras y Suministro" },
    { value: "DIR-Direccion", label: "📍 DIR – Dirección" },
    { value: "DXI-S1-Diagnostico-Imagenes-Sede-1", label: "☢️ DXI S1 – Diagnóstico por Imágenes Sede 1" },
    { value: "DXI-SF-Diagnostico-Imagenes-Sede-Santa-Fe", label: "☢️ DXI SF – Diagnóstico por Imágenes Sede Santa Fé" },
    { value: "FACT-AMB-Facturacion-Ambulatorio", label: "💳 FACT AMB – Facturación Ambulatorio" },
    { value: "FACT-INT-Facturacion-Internado", label: "💰 FACT INT – Facturación Internado" },
    { value: "FAR-Farmacia", label: "💊 FAR – Farmacia" },
    { value: "FER-Fertilidad", label: "🤰 FER – Fertilidad" },
    { value: "FUN-Fundacion", label: "🏛️ FUN – Fundación" },
    { value: "GCM-Guardia-Clinica-Medica", label: "🚑 GCM – Guardia Clínica Médica" },
    { value: "GGO-Guardia-Gineco-Obstetrica", label: "🤱 GGO – Guardia Gineco Obstétrica" },
    { value: "GPE-Guardia-Pediatrica", label: "👧 GPE – Guardia Pediátrica" },
    { value: "HDD-Hospital-de-Dia", label: "🏢 HDD – Hospital de Día" },
    { value: "HDM-Hemodinamia", label: "🫀 HDM – Hemodinamia" },
    { value: "HEM-Hemoterapia", label: "🩸 HEM – Hemoterapia" },
    { value: "HYS-Higiene-y-Seguridad", label: "🧹 HyS – Higiene y Seguridad" },
    { value: "INST-Instrumentadoras", label: "🔩 INST – Instrumentadoras" },
    { value: "INSUMED-Insumed", label: "🏷️ INSUMED" },
    { value: "INT-Internado-Adultos", label: "🛏️ INT – Internado de Adultos" },
    { value: "IPE-Internacion-Pediatrica", label: "👶 IPE – Internación Pediátrica" },
    { value: "KIN-Kinesiologia", label: "🦴 KIN – Kinesiología" },
    { value: "LAB-Laboratorio-Analisis-Clinicos", label: "🧪 LAB – Laboratorio de Análisis Clínicos" },
    { value: "LAB-FERT-Laboratorio-Fertilidad", label: "🔬 LAB FERT – Laboratorio de Fertilidad" },
    { value: "LYC-Liquidaciones-y-Convenio", label: "✉️ LyC – Liquidaciones y Convenio" },
    { value: "MAN-Mantenimiento-Edilicio", label: "🔨 MAN – Mantenimiento Edilicio" },
    { value: "NUT-Nutricion-y-Alimentacion", label: "🥗 NUT – Nutrición y Alimentación" },
    { value: "PYT-Pagos-y-Tesoreria", label: "💰 PyT – Pagos y Tesorería" },
    { value: "QUI-Quirofano", label: "🏥 QUI – Quirófano" },
    { value: "REC-S1-Recepcion-Sede-1", label: "🤒 REC S1 – Recepción Sede 1" },
    { value: "RES-Residencias-Medicas", label: "🩺 RES – Residencias Médicas" },
    { value: "RRHH-Recursos-Humanos", label: "👩‍💼 RRHH – Recursos Humanos" },
    { value: "SEG-Seguridad-Patrimonial", label: "🛡️ SEG – Seguridad Patrimonial" },
    { value: "SGC-Sistema-Gestion-Calidad", label: "📋 SGC – Sistema de Gestión de Calidad" },
    { value: "SR-Shock-Room", label: "🚨 SR – Shock Room" },
    { value: "TC-Tomografia-Computada", label: "🖥️ TC – Tomografía Computada" },
    { value: "TRM-Traumatologia", label: "🦿 TRM – Traumatología" },
    { value: "TYS-Tecnologia-y-Sistemas", label: "💻 TyS – Tecnología y Sistemas" },
    { value: "UCI-Unidad-Cuidados-Intensivos", label: "💓 UCI – Unidad de Cuidados Intensivos" },
    { value: "UTIN-Cuidados-Intensivos-Neonatales", label: "👶 UTIN – Unidad de Cuidados Intensivos Neonatales" },
    { value: "VAC-Vacunatorio", label: "💉 VAC – Vacunatorio" },
];
